### ISSUE TITLE
[Epic] k3s_server and k3s_agent tasks are not idempotent

### ISSUE THREAD

**Issue by jon-stumpf** [k3s-io/k3s-ansible#264]
The below tasks are repeated even when they are not needed.  Fixes are forthcoming.
### [k3s_server](https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml)
- [x] Download K3s binary, https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml#L13
- [x] Copy K3s service file [Single], https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml#L26
- [x] Copy config file to user home directory, https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml#L70
- [x] Add K3s autocomplete to user bashrc (#262), https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml#L78
- [x] Change server to API endpoint instead of localhost, https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_server/tasks/main.yml#L86
### [k3s_agent](https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_agent/tasks/main.yml)
- [x] Download K3s binary, https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_agent/tasks/main.yml#L13
- [x] Copy K3s service file (#268), https://github.com/k3s-io/k3s-ansible/blob/19c206d0cb448a33c869bbb8e084653e111be582/roles/k3s_agent/tasks/main.yml#L23

**Comment by dereknola** [comment]
I assume most of this was me blindly putting in `changed_when: true` for these tasks :flushed:

**Comment by dereknola** [comment]
GH being dumb and autoclosing this issue.

**Comment by alvsanand** [comment]
In step "Change server to API endpoint instead of localhost", kubeconfig must be set to "/etc/rancher/k3s/k3s.yaml". "~{{ ansible_user }}/.kube/config" is not used in the servers.

**Comment by dereknola** [comment]
Several more were addressed in https://github.com/k3s-io/k3s-ansible/pull/288

**Comment by peterklijn** [comment]
@dereknola now that https://github.com/k3s-io/k3s-ansible/pull/347 is merged, I believe all tasks are idempotent.
At least, in the setup I have running, a second run does not report any changes.

I think this issue can be closed.
